# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tztui < Formula
  desc "A terminal UI for managing and browsing system timezones."
  homepage "https://github.com/jakobnielsen/tztui"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jakobnielsen/tztui/releases/download/v1.3.0/tztui_darwin_amd64.tar.gz"
      sha256 "d52a2f85e74f1acc7aa2a9d2bbb9c666807b7b1154ee1ae2f96754945786f7f7"

      define_method(:install) do
        bin.install "tztui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jakobnielsen/tztui/releases/download/v1.3.0/tztui_darwin_arm64.tar.gz"
      sha256 "bba0d60511f10c3a6467447b7c5f4e24e9944d07842eae692e2eda62e4e77814"

      define_method(:install) do
        bin.install "tztui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jakobnielsen/tztui/releases/download/v1.3.0/tztui_linux_amd64.tar.gz"
      sha256 "146ac226d9a6f2074eceb18f3c707ab6166a19bfb6612c16ac0478b462cdcccb"
      define_method(:install) do
        bin.install "tztui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jakobnielsen/tztui/releases/download/v1.3.0/tztui_linux_arm64.tar.gz"
      sha256 "45b83e15dd6232c5cee4422ee18a5d4dbf956b2b0ac8e247715e11f32ca86f07"
      define_method(:install) do
        bin.install "tztui"
      end
    end
  end

  test do
    system "#{bin}/tztui", "--version"
  end
end
