# This file was generated by GoReleaser. DO NOT EDIT.
cask "tztui" do
  version "1.5.0"

  on_macos do
    on_intel do
      url "https://github.com/jakobnielsen/tztui/releases/download/v#{version}/tztui_darwin_amd64.tar.gz"
      sha256 "c79829a888948e5e68a0cec181bfc8b11b1ca3d4524c7de23a9f18ed119f91ed"
    end
    on_arm do
      url "https://github.com/jakobnielsen/tztui/releases/download/v#{version}/tztui_darwin_arm64.tar.gz"
      sha256 "3e00c3592383661a380fbde662829c7c8b9a13a1241ed697972fbd30410929ad"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jakobnielsen/tztui/releases/download/v#{version}/tztui_linux_amd64.tar.gz"
      sha256 "c4f529c8a815160fd896cfa6255aecd41ea048b95ffb0d7efb0ec99066c6759c"
    end
    on_arm do
      url "https://github.com/jakobnielsen/tztui/releases/download/v#{version}/tztui_linux_arm64.tar.gz"
      sha256 "22093c0bbd41e8958c5750f60291615119200359deb73ccf0905fe374db20b73"
    end
  end

  name "tztui"
  desc "A terminal UI for managing and browsing system timezones."
  homepage "https://github.com/jakobnielsen/tztui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tztui"

  # No zap stanza required

end
