# This file was generated by GoReleaser. DO NOT EDIT.
cask "tztui" do
  version "1.6.0"

  on_macos do
    on_intel do
      url "https://github.com/jakobnielsen/tztui/releases/download/v#{version}/tztui_darwin_amd64.tar.gz"
      sha256 "01a8a8721a9707d7601c714ee63dcb370c0fef2f15e9a7ca5ef63c989080684d"
    end
    on_arm do
      url "https://github.com/jakobnielsen/tztui/releases/download/v#{version}/tztui_darwin_arm64.tar.gz"
      sha256 "40b4fc77e3c1584fb265eb360db33dc682c730b19a7eac45f66bdfa46edb0582"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jakobnielsen/tztui/releases/download/v#{version}/tztui_linux_amd64.tar.gz"
      sha256 "fa2aa5808f34b842f70588706293845cc332a281bedde6f48fe7b82e7c4fdb88"
    end
    on_arm do
      url "https://github.com/jakobnielsen/tztui/releases/download/v#{version}/tztui_linux_arm64.tar.gz"
      sha256 "8b1fe2bce7ea4c014c8e288e0ce69161e0ed9742ed76db568b6ddd12cb27483f"
    end
  end

  name "tztui"
  desc "A terminal UI for managing and browsing system timezones."
  homepage "https://github.com/jakobnielsen/tztui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tztui"

  # No zap stanza required

end
