# This file was generated by GoReleaser. DO NOT EDIT.
cask "tztui" do
  version "1.3.1"

  on_macos do
    on_intel do
      url "https://github.com/jakobnielsen/tztui/releases/download/v#{version}/tztui_darwin_amd64.tar.gz"
      sha256 "5bd6aa91c000c8fc867db62470770b314ca9ffad97d40d11010c362a314328d9"
    end
    on_arm do
      url "https://github.com/jakobnielsen/tztui/releases/download/v#{version}/tztui_darwin_arm64.tar.gz"
      sha256 "82c8a21a065945913129df655abf21b7759cfcdbc901297e222b48240a0d993f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jakobnielsen/tztui/releases/download/v#{version}/tztui_linux_amd64.tar.gz"
      sha256 "d1b8604562f58bc75f035c559ad4ec9f6d9856e144450c5dd9a9266c791aec6d"
    end
    on_arm do
      url "https://github.com/jakobnielsen/tztui/releases/download/v#{version}/tztui_linux_arm64.tar.gz"
      sha256 "c06c62f74a2119daf49d71da7ac57c930d005708b4d60d5f76de3e4955700caf"
    end
  end

  name "tztui"
  desc "A terminal UI for managing and browsing system timezones."
  homepage "https://github.com/jakobnielsen/tztui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tztui"

  # No zap stanza required

end
